# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='name',
            new_name='programName',
        ),
    ]
