# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contactDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' contactDbId'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.TextField(blank=True, verbose_name=' email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instituteName',
            field=models.TextField(blank=True, verbose_name=' instituteName'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(blank=True, verbose_name=' name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='orcid',
            field=models.TextField(blank=True, verbose_name=' orcid'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.TextField(blank=True, verbose_name=' type'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='commonName',
            field=models.TextField(verbose_name=' commonName'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='cropDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donorAccessionNumber',
            field=models.TextField(blank=True, verbose_name=' donorAccessionNumber'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donorGermplasmPUI',
            field=models.TextField(blank=True, verbose_name=' donorGermplasmPUI'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donorInstituteCode',
            field=models.TextField(blank=True, verbose_name=' donorInstituteCode'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='germplasmDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Germplasm', verbose_name=' germplasmDbId'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='accessionNumber',
            field=models.TextField(blank=True, verbose_name=' accessionNumber'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='acquisitionDate',
            field=models.TextField(blank=True, verbose_name=' acquisitionDate'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='biologicalStatusOfAccessionCode',
            field=models.TextField(blank=True, verbose_name=' biologicalStatusOfAccessionCode'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='countryOfOriginCode',
            field=models.TextField(blank=True, verbose_name=' countryOfOriginCode'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='defaultDisplayName',
            field=models.TextField(verbose_name=' defaultDisplayName'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='genus',
            field=models.TextField(blank=True, verbose_name=' genus'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='germplasmDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' germplasmDbId'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='germplasmName',
            field=models.TextField(verbose_name=' germplasmName'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='germplasmPUI',
            field=models.TextField(blank=True, verbose_name=' germplasmPUI'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='instituteCode',
            field=models.TextField(verbose_name=' instituteCode'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='instituteName',
            field=models.TextField(blank=True, verbose_name=' instituteName'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='pedigree',
            field=models.TextField(blank=True, verbose_name=' pedigree'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='seedSource',
            field=models.TextField(blank=True, verbose_name=' seedSource'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='species',
            field=models.TextField(blank=True, verbose_name=' species'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='speciesAuthority',
            field=models.TextField(blank=True, verbose_name=' speciesAuthority'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='subtaxa',
            field=models.TextField(blank=True, verbose_name=' subtaxa'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='subtaxaAuthority',
            field=models.TextField(blank=True, verbose_name=' subtaxaAuthority'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='synonyms',
            field=models.TextField(blank=True, verbose_name=' synonyms'),
        ),
        migrations.AlterField(
            model_name='germplasm',
            name='typeOfGermplasmStorageCode',
            field=models.TextField(blank=True, verbose_name=' typeOfGermplasmStorageCode'),
        ),
        migrations.AlterField(
            model_name='germplasmattribute',
            name='attributeCategoryDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.GermplasmAttributeCategory', verbose_name=' attributeCategoryDbId'),
        ),
        migrations.AlterField(
            model_name='germplasmattribute',
            name='attributeDbId',
            field=models.TextField(unique=True, verbose_name=' attributeDbId'),
        ),
        migrations.AlterField(
            model_name='germplasmattribute',
            name='code',
            field=models.TextField(blank=True, verbose_name=' code'),
        ),
        migrations.AlterField(
            model_name='germplasmattribute',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='germplasmattribute',
            name='datatype',
            field=models.TextField(blank=True, verbose_name=' datatype'),
        ),
        migrations.AlterField(
            model_name='germplasmattribute',
            name='description',
            field=models.TextField(blank=True, verbose_name=' description'),
        ),
        migrations.AlterField(
            model_name='germplasmattribute',
            name='name',
            field=models.TextField(verbose_name=' name'),
        ),
        migrations.AlterField(
            model_name='germplasmattribute',
            name='uri',
            field=models.TextField(blank=True, verbose_name=' uri'),
        ),
        migrations.AlterField(
            model_name='germplasmattribute',
            name='values',
            field=models.TextField(blank=True, verbose_name=' values'),
        ),
        migrations.AlterField(
            model_name='germplasmattributecategory',
            name='attributeCategoryDbId',
            field=models.TextField(unique=True, verbose_name=' attributeCategoryDbId'),
        ),
        migrations.AlterField(
            model_name='germplasmattributecategory',
            name='attributeCategoryName',
            field=models.TextField(blank=True, verbose_name=' attributeCategoryName'),
        ),
        migrations.AlterField(
            model_name='germplasmattributecategory',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='germplasmattributevalue',
            name='attributeDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.GermplasmAttribute', verbose_name=' attributeDbId'),
        ),
        migrations.AlterField(
            model_name='germplasmattributevalue',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='germplasmattributevalue',
            name='determinedDate',
            field=models.TextField(blank=True, verbose_name=' determinedDate'),
        ),
        migrations.AlterField(
            model_name='germplasmattributevalue',
            name='germplasmDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Germplasm', verbose_name=' germplasmDbId'),
        ),
        migrations.AlterField(
            model_name='germplasmattributevalue',
            name='value',
            field=models.TextField(verbose_name=' value'),
        ),
        migrations.AlterField(
            model_name='location',
            name='abbreviation',
            field=models.TextField(blank=True, verbose_name=' abbreviation'),
        ),
        migrations.AlterField(
            model_name='location',
            name='altitude',
            field=models.TextField(blank=True, verbose_name=' altitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='countryCode',
            field=models.TextField(blank=True, verbose_name=' countryCode'),
        ),
        migrations.AlterField(
            model_name='location',
            name='countryName',
            field=models.TextField(blank=True, verbose_name=' countryName'),
        ),
        migrations.AlterField(
            model_name='location',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='location',
            name='instituteAddress',
            field=models.TextField(blank=True, verbose_name=' instituteAddress'),
        ),
        migrations.AlterField(
            model_name='location',
            name='instituteName',
            field=models.TextField(blank=True, verbose_name=' instituteName'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.TextField(blank=True, verbose_name=' latitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' locationDbId'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.TextField(blank=True, verbose_name=' longitude'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(blank=True, verbose_name=' name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.TextField(blank=True, verbose_name=' type'),
        ),
        migrations.AlterField(
            model_name='locationadditionalinfo',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='locationadditionalinfo',
            name='key',
            field=models.TextField(verbose_name=' key'),
        ),
        migrations.AlterField(
            model_name='locationadditionalinfo',
            name='locationDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Location', verbose_name=' locationDbId'),
        ),
        migrations.AlterField(
            model_name='locationadditionalinfo',
            name='value',
            field=models.TextField(verbose_name=' value'),
        ),
        migrations.AlterField(
            model_name='map',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='map',
            name='mapDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' mapDbId'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='analysisMethods',
            field=models.TextField(blank=True, verbose_name=' analysisMethods'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='defaultDisplayName',
            field=models.TextField(blank=True, verbose_name=' defaultDisplayName'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='markerDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' markerDbId'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='refAlt',
            field=models.TextField(blank=True, verbose_name=' refAlt'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='synonyms',
            field=models.TextField(blank=True, verbose_name=' synonyms'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='type',
            field=models.TextField(blank=True, verbose_name=' type'),
        ),
        migrations.AlterField(
            model_name='markerprofile',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='markerprofile',
            name='markerProfileDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' markerProfileDbId'),
        ),
        migrations.AlterField(
            model_name='method',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='method',
            name='methodDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' methodDbId'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='collector',
            field=models.TextField(blank=True, verbose_name=' collector'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observationDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' observationDbId'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observationTimeStamp',
            field=models.TextField(blank=True, verbose_name=' observationTimeStamp'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observationUnitDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.ObservationUnit', verbose_name=' observationUnitDbId'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observationVariableDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.ObservationVariable', verbose_name=' observationVariableDbId'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='seasonDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Season', verbose_name=' seasonDbId'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='value',
            field=models.TextField(blank=True, verbose_name=' value'),
        ),
        migrations.AlterField(
            model_name='observationunit',
            name='blockNumber',
            field=models.TextField(blank=True, verbose_name=' blockNumber'),
        ),
        migrations.AlterField(
            model_name='observationunit',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='observationunit',
            name='entryNumber',
            field=models.TextField(blank=True, verbose_name=' entryNumber'),
        ),
        migrations.AlterField(
            model_name='observationunit',
            name='entryType',
            field=models.TextField(blank=True, verbose_name=' entryType'),
        ),
        migrations.AlterField(
            model_name='observationunit',
            name='germplasmDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Germplasm', verbose_name=' germplasmDbId'),
        ),
        migrations.AlterField(
            model_name='observationunit',
            name='name',
            field=models.TextField(verbose_name=' name'),
        ),
        migrations.AlterField(
            model_name='observationunit',
            name='observationUnitDbId',
            field=models.TextField(unique=True, verbose_name=' observationUnitDbId'),
        ),
        migrations.AlterField(
            model_name='observationunit',
            name='observationUnitLevel',
            field=models.TextField(blank=True, verbose_name=' observationUnitLevel'),
        ),
        migrations.AlterField(
            model_name='observationunit',
            name='observationUnitLevels',
            field=models.TextField(blank=True, verbose_name=' observationUnitLevels'),
        ),
        migrations.AlterField(
            model_name='observationunit',
            name='plantNumber',
            field=models.TextField(blank=True, verbose_name=' plantNumber'),
        ),
        migrations.AlterField(
            model_name='observationunit',
            name='plotNumber',
            field=models.TextField(blank=True, verbose_name=' plotNumber'),
        ),
        migrations.AlterField(
            model_name='observationunit',
            name='replicate',
            field=models.TextField(blank=True, verbose_name=' replicate'),
        ),
        migrations.AlterField(
            model_name='observationunit',
            name='studyDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Study', verbose_name=' studyDbId'),
        ),
        migrations.AlterField(
            model_name='observationunit',
            name='x',
            field=models.TextField(blank=True, verbose_name=' x'),
        ),
        migrations.AlterField(
            model_name='observationunit',
            name='y',
            field=models.TextField(blank=True, verbose_name=' y'),
        ),
        migrations.AlterField(
            model_name='observationunittreatment',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='observationunittreatment',
            name='factor',
            field=models.TextField(verbose_name=' factor'),
        ),
        migrations.AlterField(
            model_name='observationunittreatment',
            name='modality',
            field=models.TextField(verbose_name=' modality'),
        ),
        migrations.AlterField(
            model_name='observationunittreatment',
            name='observationUnitDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.ObservationUnit', verbose_name=' observationUnitDbId'),
        ),
        migrations.AlterField(
            model_name='observationunitxref',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='observationunitxref',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' id'),
        ),
        migrations.AlterField(
            model_name='observationunitxref',
            name='observationUnitDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.ObservationUnit', verbose_name=' observationUnitDbId'),
        ),
        migrations.AlterField(
            model_name='observationunitxref',
            name='source',
            field=models.TextField(verbose_name=' source'),
        ),
        migrations.AlterField(
            model_name='observationvariable',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='observationvariable',
            name='methodDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Method', verbose_name=' methodDbId'),
        ),
        migrations.AlterField(
            model_name='observationvariable',
            name='observationVariableDbId',
            field=models.TextField(unique=True, verbose_name=' observationVariableDbId'),
        ),
        migrations.AlterField(
            model_name='observationvariable',
            name='ontologyDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Ontology', verbose_name=' ontologyDbId'),
        ),
        migrations.AlterField(
            model_name='observationvariable',
            name='scaleDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Scale', verbose_name=' scaleDbId'),
        ),
        migrations.AlterField(
            model_name='observationvariable',
            name='traitDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Trait', verbose_name=' traitDbId'),
        ),
        migrations.AlterField(
            model_name='ontology',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='ontology',
            name='ontologyDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' ontologyDbId'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='germplasmDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedigreeObject', to='jsonapi.Germplasm', verbose_name=' germplasmDbId'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='parent1Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedigreeChild1', to='jsonapi.Germplasm', verbose_name=' parent1Id'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='parent2Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedigreeChild2', to='jsonapi.Germplasm', verbose_name=' parent2Id'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='pedigree',
            field=models.TextField(verbose_name=' pedigree'),
        ),
        migrations.AlterField(
            model_name='program',
            name='abbreviation',
            field=models.TextField(blank=True, verbose_name=' abbreviation'),
        ),
        migrations.AlterField(
            model_name='program',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='program',
            name='leadPerson',
            field=models.TextField(blank=True, verbose_name=' leadPerson'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.TextField(verbose_name=' name'),
        ),
        migrations.AlterField(
            model_name='program',
            name='objective',
            field=models.TextField(blank=True, verbose_name=' objective'),
        ),
        migrations.AlterField(
            model_name='program',
            name='programDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' programDbId'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sampleDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' sampleDbId'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='scale',
            name='scaleDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' scaleDbId'),
        ),
        migrations.AlterField(
            model_name='season',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.TextField(blank=True, verbose_name=' season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='seasonDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' seasonDbId'),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.TextField(blank=True, verbose_name=' year'),
        ),
        migrations.AlterField(
            model_name='study',
            name='active',
            field=models.NullBooleanField(verbose_name=' active'),
        ),
        migrations.AlterField(
            model_name='study',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='study',
            name='description',
            field=models.TextField(blank=True, verbose_name=' description'),
        ),
        migrations.AlterField(
            model_name='study',
            name='endDate',
            field=models.TextField(blank=True, verbose_name=' endDate'),
        ),
        migrations.AlterField(
            model_name='study',
            name='lastUpdateTimestamp',
            field=models.TextField(blank=True, verbose_name=' lastUpdateTimestamp'),
        ),
        migrations.AlterField(
            model_name='study',
            name='lastUpdateVersion',
            field=models.TextField(blank=True, verbose_name=' lastUpdateVersion'),
        ),
        migrations.AlterField(
            model_name='study',
            name='license',
            field=models.TextField(blank=True, verbose_name=' license'),
        ),
        migrations.AlterField(
            model_name='study',
            name='locationDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Location', verbose_name=' locationDbId'),
        ),
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.TextField(verbose_name=' name'),
        ),
        migrations.AlterField(
            model_name='study',
            name='startDate',
            field=models.TextField(blank=True, verbose_name=' startDate'),
        ),
        migrations.AlterField(
            model_name='study',
            name='studyDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' studyDbId'),
        ),
        migrations.AlterField(
            model_name='study',
            name='studyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.StudyType', verbose_name=' studyType'),
        ),
        migrations.AlterField(
            model_name='study',
            name='trialDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Trial', verbose_name=' trialDbId'),
        ),
        migrations.AlterField(
            model_name='studyadditionalinfo',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='studyadditionalinfo',
            name='key',
            field=models.TextField(verbose_name=' key'),
        ),
        migrations.AlterField(
            model_name='studyadditionalinfo',
            name='studyDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Study', verbose_name=' studyDbId'),
        ),
        migrations.AlterField(
            model_name='studyadditionalinfo',
            name='value',
            field=models.TextField(verbose_name=' value'),
        ),
        migrations.AlterField(
            model_name='studycontact',
            name='contactDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Contact', verbose_name=' contactDbId'),
        ),
        migrations.AlterField(
            model_name='studycontact',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='studycontact',
            name='studyDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Study', verbose_name=' studyDbId'),
        ),
        migrations.AlterField(
            model_name='studydatalink',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='studydatalink',
            name='name',
            field=models.TextField(blank=True, verbose_name=' name'),
        ),
        migrations.AlterField(
            model_name='studydatalink',
            name='studyDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Study', verbose_name=' studyDbId'),
        ),
        migrations.AlterField(
            model_name='studydatalink',
            name='type',
            field=models.TextField(blank=True, verbose_name=' type'),
        ),
        migrations.AlterField(
            model_name='studydatalink',
            name='url',
            field=models.TextField(verbose_name=' url'),
        ),
        migrations.AlterField(
            model_name='studyseason',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='studyseason',
            name='seasonDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Season', verbose_name=' seasonDbId'),
        ),
        migrations.AlterField(
            model_name='studyseason',
            name='studyDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Study', verbose_name=' studyDbId'),
        ),
        migrations.AlterField(
            model_name='studytype',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='studytype',
            name='description',
            field=models.TextField(blank=True, verbose_name=' description'),
        ),
        migrations.AlterField(
            model_name='studytype',
            name='name',
            field=models.TextField(unique=True, verbose_name=' name'),
        ),
        migrations.AlterField(
            model_name='taxonxref',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='taxonxref',
            name='rank',
            field=models.TextField(blank=True, verbose_name=' rank'),
        ),
        migrations.AlterField(
            model_name='taxonxref',
            name='source',
            field=models.TextField(verbose_name=' source'),
        ),
        migrations.AlterField(
            model_name='taxonxref',
            name='taxonDbId',
            field=models.TextField(unique=True, verbose_name=' taxonDbId'),
        ),
        migrations.AlterField(
            model_name='taxonxrefgermplasm',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='taxonxrefgermplasm',
            name='germplasmDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Germplasm', verbose_name=' germplasmDbId'),
        ),
        migrations.AlterField(
            model_name='taxonxrefgermplasm',
            name='taxonDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.TaxonXref', verbose_name=' taxonDbId'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='traitDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' traitDbId'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='active',
            field=models.NullBooleanField(verbose_name=' active'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='datasetAuthorshipDatasetPUI',
            field=models.TextField(blank=True, verbose_name=' datasetAuthorshipDatasetPUI'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='datasetAuthorshipLicence',
            field=models.TextField(blank=True, verbose_name=' datasetAuthorshipLicence'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='endDate',
            field=models.TextField(blank=True, verbose_name=' endDate'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='name',
            field=models.TextField(verbose_name=' name'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='programDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Program', verbose_name=' programDbId'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='startDate',
            field=models.TextField(blank=True, verbose_name=' startDate'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='trialDbId',
            field=models.TextField(primary_key=True, serialize=False, verbose_name=' trialDbId'),
        ),
        migrations.AlterField(
            model_name='trialadditionalinfo',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='trialadditionalinfo',
            name='key',
            field=models.TextField(verbose_name=' key'),
        ),
        migrations.AlterField(
            model_name='trialadditionalinfo',
            name='trialDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Trial', verbose_name=' trialDbId'),
        ),
        migrations.AlterField(
            model_name='trialadditionalinfo',
            name='value',
            field=models.TextField(verbose_name=' value'),
        ),
        migrations.AlterField(
            model_name='trialcontact',
            name='contactDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Contact', verbose_name=' contactDbId'),
        ),
        migrations.AlterField(
            model_name='trialcontact',
            name='cropDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Crop', verbose_name=' cropDbId'),
        ),
        migrations.AlterField(
            model_name='trialcontact',
            name='trialDbId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonapi.Trial', verbose_name=' trialDbId'),
        ),
    ]
