# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0004_auto_20170804_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AddField(
            model_name='location',
            name='locationName',
            field=models.TextField(blank=True, verbose_name=' locationName'),
        ),
        migrations.AlterField(
            model_name='program',
            name='programName',
            field=models.TextField(verbose_name=' programName'),
        ),
        migrations.AlterField(
            model_name='study',
            name='studyName',
            field=models.TextField(verbose_name=' studyName'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='trialName',
            field=models.TextField(verbose_name=' trialName'),
        ),
    ]
