# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0005_auto_20170804_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='locationName',
        ),
        migrations.RemoveField(
            model_name='program',
            name='programName',
        ),
        migrations.RemoveField(
            model_name='study',
            name='studyName',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='trialName',
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.TextField(blank=True, verbose_name=' name'),
        ),
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.TextField(default='', verbose_name=' name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='name',
            field=models.TextField(default='', verbose_name=' name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trial',
            name='name',
            field=models.TextField(default='', verbose_name=' name'),
            preserve_default=False,
        ),
    ]
