# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0006_auto_20170811_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObservationUnitTreatment',
            new_name='Treatment',
        ),
        migrations.RenameField(
            model_name='observationunit',
            old_name='observationUnitLevel',
            new_name='observationLevel',
        ),
        migrations.RenameField(
            model_name='observationunit',
            old_name='observationUnitLevels',
            new_name='observationLevels',
        ),
        migrations.AddField(
            model_name='observationvariable',
            name='observationVariableName',
            field=models.TextField(blank=True, verbose_name=' observationVariableName'),
        ),
    ]
