# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-29 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0007_auto_20170921_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontology',
            name='name',
            field=models.TextField(default='', verbose_name=' name'),
            preserve_default=False,
        ),
    ]
