# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-03 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RichText',
            new_name='HTMLpage',
        ),
    ]
