# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-03 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180803_1024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HTMLpage',
            new_name='HTML_page',
        ),
    ]
