# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-03 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180803_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html_page',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
